version: '3'
services:
    app:
        build:
            context: .
            dockerfile: src/backend/Dockerfile
        volumes:
            - ./src:/var/www
        environment:
            - "DB_CONNECTION=mysql"
            - "DB_HOST=mysql"
            - "DB_PORT=3306"
            - "APP_PORT=${APP_PORT}"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        networks:
            - laravel_crm
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_crm
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_crm

volumes:
    db_data:
networks:
    laravel_crm:
        driver: bridge

