version: '3'
services:
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_crm
    backend:
        build:
            context: .
            dockerfile: src/backend/Dockerfile
        restart: unless-stopped
        volumes:
            - ./src/backend:/var/www/backend
            - ./files/entrypoint.sh:/usr/local/bin/entrypoint.sh # Add this line to mount the entrypoint script into the container.
        environment:
            - "DB_CONNECTION=mysql"
            - "DB_HOST=mysql"
            - "DB_PORT=3306"
            - "APP_PORT=${APP_PORT}"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
        networks:
            - laravel_crm
    fronted:
        build:
            context: .
            dockerfile: src/fronted/Dockerfile
        restart: unless-stopped
        volumes:
            - ./src/fronted:/var/www/fronted
        networks:
            - laravel_crm
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./files/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_crm
volumes:
    db_data:
networks:
    laravel_crm:
        driver: bridge

